name: magicinsta
favicon: null
layout_spectrum: 0.3225487207528204
typography_spectrum: 0.4420012349728495
title: Engajamento de Rede sociais para eventos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0978261202108115
  lightness: 0.8900630509015173
  saturation: 0.8163693728856742
  rhythmicContrast: 0.22420059703290462
purpose: []
