name: magicinsta
favicon: null
layout_spectrum: 0.24884
typography_spectrum: 0.4420012349728495
title: Engajamento de Rede sociais para eventos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#38c6d2'
    - '#232742'
    - '#f3ede1'
    - '#c22f3f'
    - '#bb9a84'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
